# Discovering Data Structure Definitions (DSDs) in BIS SDMX

## Overview

In the previous notebook, we discovered the list of **Dataflows** exposed by the Bank for International Settlements (BIS). A Dataflow tells us **what datasets are available**, but it does not describe **how those datasets are organized**.

This notebook explores the next layer of the SDMX Information Model — the **Data Structure Definition (DSD)**.

A DSD defines the schema of a dataset, including:

- Dimensions (e.g., Country, Frequency, Time)
- Measures (e.g., Observation Value)
- Attributes (e.g., Units, Status)
- References to codelists that define valid values

Think of a DSD as the SDMX equivalent of running:

```sql
DESCRIBE TABLE credit_statistics;
```

on a relational database.

Understanding the DSD allows us to understand a dataset **without downloading a single observation**.

---

## Objectives

By the end of this notebook, we will be able to:

- Connect to the BIS SDMX API
- Retrieve all available Dataflows
- Select a Dataflow
- Retrieve its Data Structure Definition (DSD)
- Explore its Dimensions
- Explore its Measures
- Explore its Attributes

The next notebook will build upon this knowledge to discover the allowed values (Codelists) associated with each Dimension.

In [ ]:
import sdmx
import pandas as pd

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

+

In [ ]:
# ----------------------------------------------------
# Connect to BIS SDMX API
# ----------------------------------------------------

client = sdmx.Client("BIS")
print("Connected to BIS successfully.")

Connected to BIS successfully.

In [ ]:
# ----------------------------------------------------
# Retrieve all dataflows
# ----------------------------------------------------


response = client.dataflow()

flows = response.dataflow

print(f"Total Dataflows : {len(flows)}")

Total Dataflows : 29

In [8]:
# ----------------------------------------------------
# Convert into DataFrame
# ----------------------------------------------------

records = []

for flow_id, flow in flows.items():

    try:
        name = flow.name.en
    except Exception:
        name = str(flow.name)

    try:
        description = flow.description.en
    except Exception:
        description = ""

    try:
        structure = flow.structure.id
    except Exception:
        structure = ""

    records.append(
        {
            "Flow ID": flow_id,
            "Name": name,
            "Description": description,
            "Structure": structure,
        }
    )

df_flows = pd.DataFrame(records)
df_flows = df_flows.sort_values("Flow ID").reset_index(drop=True)
df_flows

,Flow ID,Name,Description,Structure
0,BIS_REL_CAL,BIS_RELEASE_CALENDAR,,BIS_RELEASE_CALENDAR
1,WS_CBPOL,Central bank policy rates,The interest rate which best captures the mone...,BIS_CBPOL
2,WS_CBS_PUB,Consolidated banking,,BIS_CBS
3,WS_CBTA,Central bank total assets,Tracks the evolution of the size of central ba...,CBTA
4,WS_CPMI_CASHLESS,CPMI cashless payments,Payment statistics covering indicators of reta...,CPMI_CASHLESS
5,WS_CPMI_CT1,CPMI comparative tables type 1,CPMI comparative tables type 1,CPMI_CT1
6,WS_CPMI_CT2,CPMI comparative tables type 2,CPMI comparative tables type 2,CPMI_CT2
7,WS_CPMI_DEVICES,CPMI payment devices,Payment statistics covering the number of card...,CPMI_DEVICES
8,WS_CPMI_INSTITUT,CPMI institutions,Payment statistics covering institutions offer...,CPMI_INSTITUTIONS
9,WS_CPMI_MACRO,CPMI macro,General macroeconomic indicators and monetary ...,CPMI_MACRO
10,WS_CPMI_PARTICIP,CPMI participants,Payment statistics covering participation in f...,CPMI_PARTICIPANTS
11,WS_CPMI_SYSTEMS,CPMI systems,Payment statistics covering activities in fina...,CPMI_SYSTEMS
12,WS_CPP,Commercial property prices,,BIS_PROP_PRICES
13,WS_CREDIT_GAP,Credit-to-GDP gaps,,BIS_CREDIT_GAP
14,WS_DEBT_SEC2_PUB,International debt securities (BIS-compiled),,BIS_DEBT_SEC2
15,WS_DER_OTC_TOV,OTC derivatives turnover,OTC derivatives and FX spot - turnover,BIS_DER
16,WS_DPP,Detailed residential property prices,,BIS_PROP_PRICES
17,WS_DSR,Debt service ratios,Debt service costs - comprising interest payme...,BIS_DSR
18,WS_EER,Effective exchange rates,Weighted average of bilateral exchange rates. ...,BIS_EER
19,WS_GLI,Global liquidity indicators,,BIS_GLI
20,WS_LBS_D_PUB,Locational banking,,BIS_LBS_DISS
21,WS_LONG_CPI,Consumer prices statistics,An index that measures the average change in t...,BIS_LONG_CPI
22,WS_NA_SEC_C3,BIS debt securities statistics,,NA_SEC
23,WS_NA_SEC_DSS,Debt securities statistics,,NA_SEC
24,WS_OTC_DERIV2,OTC derivatives outstanding,,BIS_DER
25,WS_SPP,Selected residential property prices,,BIS_SELECTED_PP
26,WS_TC,Total credit,,BIS_TOTAL_CREDIT
27,WS_XRU,US dollar exchange rates,The price of one country's currency in relatio...,BIS_XR
28,WS_XTD_DERIV,Exchange-traded derivatives,,BIS_XTD_DERIV

## Selecting a Dataflow

Every Dataflow is associated with exactly one **Data Structure Definition (DSD)**.

For demonstration purposes, we will inspect one Dataflow.

You may replace the `FLOW_ID` below with any valid BIS Dataflow ID.

In [ ]:
FLOW_ID = "WS_TC"

if FLOW_ID not in flows:
    raise ValueError(f"{FLOW_ID} is not a valid BIS Dataflow ID.")

flow = flows[FLOW_ID]

# ----------------------------------------------------
# Inspect Dataflow object
# ----------------------------------------------------
print(flow)
print("="*70)
print(flow.name)
print("="*70)
print(type(flow))

WS_TC
======================================================================
Total credit
======================================================================
<class 'sdmx.model.v21.DataflowDefinition'>

In [ ]:
# ----------------------------------------------------
# Inspect Available Attributes
# ----------------------------------------------------

dir(flow)

['__annotations__',
 '__class__',
 '__dataclass_fields__',
 '__dataclass_params__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__match_args__',
 '__module__',
 '__ne__',
 '__new__',
 '__post_init__',
 '__reduce__',
 '__reduce_ex__',
 '__replace__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__static_attributes__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_description',
 '_name',
 '_preserve',
 '_repr_kw',
 '_urn',
 'annotations',
 'compare',
 'description',
 'eval_annotation',
 'get_annotation',
 'id',
 'is_external_reference',
 'is_final',
 'iter_keys',
 'maintainer',
 'name',
 'pop_annotation',
 'service_url',
 'structure',
 'structure_url',
 'uri',
 'urn',
 'valid_from',
 'valid_to',
 'version']

In [14]:
# ----------------------------------------------------
# Check the linked structure
# ----------------------------------------------------

print(flow.structure)

BIS_TOTAL_CREDIT

In [16]:
# ----------------------------------------------------
# Inspect the structure reference
# ----------------------------------------------------
print(type(flow.structure))
print("="*70)
print(dir(flow.structure))

<class 'sdmx.model.v21.DataStructureDefinition'>
======================================================================
['ConstraintType', 'MemberSelection', 'MemberValue', '__annotations__', '__class__', '__dataclass_fields__', '__dataclass_params__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__firstlineno__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__match_args__', '__module__', '__ne__', '__new__', '__post_init__', '__reduce__', '__reduce_ex__', '__replace__', '__repr__', '__setattr__', '__sizeof__', '__slots__', '__static_attributes__', '__str__', '__subclasshook__', '__weakref__', '_cl_fields', '_description', '_group_dimensions', '_name', '_preserve', '_repr_kw', '_urn', 'annotations', 'attributes', 'compare', 'description', 'dimensions', 'eval_annotation', 'from_keys', 'get_annotation', 'group_dimensions', 'grouping', 'id', 'is_external_reference', 'is_final', 'iter_keys', 'maintainer', 'make_constraint', 'make_key', 'measures', 'name', 'pop_annotation', 'replace_grouping', 'service_url', 'structure_url', 'uri', 'urn', 'valid_from', 'valid_to', 'version']

In [18]:
# ----------------------------------------------------
# Discovering the linked DSD
# A Dataflow contains a reference to the Data Structure Definition (DSD) that describes the dataset.
# Let's inspect that relationship.
# ----------------------------------------------------
print("DSD ID :", flow.structure.id)

DSD ID : BIS_TOTAL_CREDIT

In [ ]:
dsd_response = client.get(
    "datastructure",
    resource_id=flow.structure.id
)

# If your version of sdmx1 exposes client.datastructure() instead of client.get(), replace this cell with:

# dsd_response = client.datastructure(resource_id=flow.structure.id)

In [20]:
print(type(dsd_response))

dir(dsd_response)

<class 'sdmx.message.StructureMessage'>

['__annotations__',
 '__class__',
 '__contains__',
 '__dataclass_fields__',
 '__dataclass_params__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__match_args__',
 '__module__',
 '__ne__',
 '__new__',
 '__post_init__',
 '__reduce__',
 '__reduce_ex__',
 '__replace__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_categorisation',
 '_category_scheme',
 '_codelist',
 '_collections',
 '_concept_scheme',
 '_constraint',
 '_custom_type_scheme',
 '_dataflow',
 '_hierarchical_codelist',
 '_hierarchy',
 '_metadataflow',
 '_metadatastructure',
 '_name_personalisation_scheme',
 '_organisation_scheme',
 '_provisionagreement',
 '_ruleset_scheme',
 '_structure',
 '_structureset',
 '_transformation_scheme',
 '_user_defined_operator_scheme',
 '_valuelist',
 '_vtl_mapping_scheme',
 'add',
 'categorisation',
 'category_scheme',
 'codelist',
 'compare',
 'concept_scheme',
 'constraint',
 'custom_type_scheme',
 'dataflow',
 'footer',
 'get',
 'header',
 'hierarchical_codelist',
 'hierarchy',
 'iter_collections',
 'iter_objects',
 'metadataflow',
 'metadatastructure',
 'name_personalisation_scheme',
 'objects',
 'organisation_scheme',
 'provisionagreement',
 'response',
 'ruleset_scheme',
 'structure',
 'structureset',
 'transformation_scheme',
 'user_defined_operator_scheme',
 'valuelist',
 'version',
 'vtl_mapping_scheme']

In [21]:
dsd = next(iter(dsd_response.structure.values()))

dsd

# Exploring the DSD

The DSD contains three primary components that define the structure of a dataset:

- Dimensions
- Measures
- Attributes

Let's inspect each of them individually.

### ***********************
### Exploring Dimensions
### ***********************

In [24]:
dsd.dimensions

DimensionDescriptor(annotations=[], id='DimensionDescriptor', uri=None, urn='urn:sdmx:org.sdmx.infomodel.datastructure.DimensionDescriptor=BIS:BIS_TOTAL_CREDIT(2.0).DimensionDescriptor', components=[<Dimension FREQ>, <Dimension BORROWERS_CTY>, <Dimension TC_BORROWERS>, <Dimension TC_LENDERS>, <Dimension VALUATION>, <Dimension UNIT_TYPE>, <Dimension TC_ADJUST>, <TimeDimension TIME_PERIOD>])

In [25]:
first_dim = dsd.dimensions[0]

print(type(first_dim))

print(first_dim)

print(dir(first_dim))

<class 'sdmx.model.common.Dimension'>
FREQ
['__annotations__', '__class__', '__contains__', '__dataclass_fields__', '__dataclass_params__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__firstlineno__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__match_args__', '__module__', '__ne__', '__new__', '__post_init__', '__reduce__', '__reduce_ex__', '__replace__', '__repr__', '__setattr__', '__sizeof__', '__slots__', '__static_attributes__', '__str__', '__subclasshook__', '__weakref__', '_preserve', '_urn', 'annotations', 'compare', 'concept_identity', 'concept_role', 'eval_annotation', 'get_annotation', 'id', 'local_representation', 'order', 'pop_annotation', 'uri', 'urn']

In [26]:
dim.id

'FREQ'

In [29]:
dim.concept_identity

In [30]:
dim.concept_identity.name

en: Frequency

In [ ]:
# ----------------------------------------------------
# Inspect every property
# ----------------------------------------------------

for dim in dsd.dimensions:
    print("="*60)
    print("ID:", dim.id)

    for attr in dir(dim):
        if not attr.startswith("_"):
            try:
                print(attr, ":", getattr(dim, attr))
            except:
                pass

============================================================
ID: FREQ
annotations : []
compare : <bound method Comparable.compare of <Dimension FREQ>>
concept_identity : FREQ
concept_role : None
eval_annotation : <bound method AnnotableArtefact.eval_annotation of <Dimension FREQ>>
get_annotation : <bound method AnnotableArtefact.get_annotation of <Dimension FREQ>>
id : FREQ
local_representation : <Representation: CL_FREQ, [Facet(type=FacetType(is_sequence='false', min_length=1, max_length=1, min_value=None, max_value=None, start_value=None, end_value=None, interval=None, time_interval=None, decimals=None, pattern=None, start_time=None, end_time=None, sentinel_values=None), value=None, value_type=<FacetValueType.string: 1>)]>
order : 1
pop_annotation : <bound method AnnotableArtefact.pop_annotation of <Dimension FREQ>>
uri : None
urn : urn:sdmx:org.sdmx.infomodel.datastructure.Dimension=BIS:BIS_TOTAL_CREDIT(2.0).FREQ
============================================================
ID: BORROWERS_CTY
annotations : []
compare : <bound method Comparable.compare of <Dimension BORROWERS_CTY>>
concept_identity : BORROWERS_CTY
concept_role : None
eval_annotation : <bound method AnnotableArtefact.eval_annotation of <Dimension BORROWERS_CTY>>
get_annotation : <bound method AnnotableArtefact.get_annotation of <Dimension BORROWERS_CTY>>
id : BORROWERS_CTY
local_representation : <Representation: CL_AREA, [Facet(type=FacetType(is_sequence='false', min_length=2, max_length=2, min_value=None, max_value=None, start_value=None, end_value=None, interval=None, time_interval=None, decimals=None, pattern=None, start_time=None, end_time=None, sentinel_values=None), value=None, value_type=<FacetValueType.string: 1>)]>
order : 2
pop_annotation : <bound method AnnotableArtefact.pop_annotation of <Dimension BORROWERS_CTY>>
uri : None
urn : urn:sdmx:org.sdmx.infomodel.datastructure.Dimension=BIS:BIS_TOTAL_CREDIT(2.0).BORROWERS_CTY
============================================================
ID: TC_BORROWERS
annotations : [Annotation(id=None, title='HCL', type='urn:sdmx:org.sdmx.infomodel.codelist.HierarchicalCodelist=BIS:WS_TC_BORROWERS(1.0)', url=None, text=)]
compare : <bound method Comparable.compare of <Dimension TC_BORROWERS>>
concept_identity : TC_BORROWERS
concept_role : None
eval_annotation : <bound method AnnotableArtefact.eval_annotation of <Dimension TC_BORROWERS>>
get_annotation : <bound method AnnotableArtefact.get_annotation of <Dimension TC_BORROWERS>>
id : TC_BORROWERS
local_representation : <Representation: CL_TC_BORROWERS, [Facet(type=FacetType(is_sequence='false', min_length=1, max_length=1, min_value=None, max_value=None, start_value=None, end_value=None, interval=None, time_interval=None, decimals=None, pattern=None, start_time=None, end_time=None, sentinel_values=None), value=None, value_type=<FacetValueType.string: 1>)]>
order : 3
pop_annotation : <bound method AnnotableArtefact.pop_annotation of <Dimension TC_BORROWERS>>
uri : None
urn : urn:sdmx:org.sdmx.infomodel.datastructure.Dimension=BIS:BIS_TOTAL_CREDIT(2.0).TC_BORROWERS
============================================================
ID: TC_LENDERS
annotations : []
compare : <bound method Comparable.compare of <Dimension TC_LENDERS>>
concept_identity : TC_LENDERS
concept_role : None
eval_annotation : <bound method AnnotableArtefact.eval_annotation of <Dimension TC_LENDERS>>
get_annotation : <bound method AnnotableArtefact.get_annotation of <Dimension TC_LENDERS>>
id : TC_LENDERS
local_representation : <Representation: CL_TC_LENDERS, [Facet(type=FacetType(is_sequence='false', min_length=1, max_length=1, min_value=None, max_value=None, start_value=None, end_value=None, interval=None, time_interval=None, decimals=None, pattern=None, start_time=None, end_time=None, sentinel_values=None), value=None, value_type=<FacetValueType.string: 1>)]>
order : 4
pop_annotation : <bound method AnnotableArtefact.pop_annotation of <Dimension TC_LENDERS>>
uri : None
urn : urn:sdmx:org.sdmx.infomodel.datastructure.Dimension=BIS:BIS_TOTAL_CREDIT(2.0).TC_LENDERS
============================================================
ID: VALUATION
annotations : []
compare : <bound method Comparable.compare of <Dimension VALUATION>>
concept_identity : VALUATION
concept_role : None
eval_annotation : <bound method AnnotableArtefact.eval_annotation of <Dimension VALUATION>>
get_annotation : <bound method AnnotableArtefact.get_annotation of <Dimension VALUATION>>
id : VALUATION
local_representation : <Representation: CL_VALUATION, [Facet(type=FacetType(is_sequence='false', min_length=1, max_length=1, min_value=None, max_value=None, start_value=None, end_value=None, interval=None, time_interval=None, decimals=None, pattern=None, start_time=None, end_time=None, sentinel_values=None), value=None, value_type=<FacetValueType.string: 1>)]>
order : 5
pop_annotation : <bound method AnnotableArtefact.pop_annotation of <Dimension VALUATION>>
uri : None
urn : urn:sdmx:org.sdmx.infomodel.datastructure.Dimension=BIS:BIS_TOTAL_CREDIT(2.0).VALUATION
============================================================
ID: UNIT_TYPE
annotations : []
compare : <bound method Comparable.compare of <Dimension UNIT_TYPE>>
concept_identity : UNIT_TYPE
concept_role : None
eval_annotation : <bound method AnnotableArtefact.eval_annotation of <Dimension UNIT_TYPE>>
get_annotation : <bound method AnnotableArtefact.get_annotation of <Dimension UNIT_TYPE>>
id : UNIT_TYPE
local_representation : <Representation: CL_BIS_UNIT, [Facet(type=FacetType(is_sequence='false', min_length=3, max_length=3, min_value=None, max_value=None, start_value=None, end_value=None, interval=None, time_interval=None, decimals=None, pattern=None, start_time=None, end_time=None, sentinel_values=None), value=None, value_type=<FacetValueType.string: 1>)]>
order : 6
pop_annotation : <bound method AnnotableArtefact.pop_annotation of <Dimension UNIT_TYPE>>
uri : None
urn : urn:sdmx:org.sdmx.infomodel.datastructure.Dimension=BIS:BIS_TOTAL_CREDIT(2.0).UNIT_TYPE
============================================================
ID: TC_ADJUST
annotations : []
compare : <bound method Comparable.compare of <Dimension TC_ADJUST>>
concept_identity : TC_ADJUST
concept_role : None
eval_annotation : <bound method AnnotableArtefact.eval_annotation of <Dimension TC_ADJUST>>
get_annotation : <bound method AnnotableArtefact.get_annotation of <Dimension TC_ADJUST>>
id : TC_ADJUST
local_representation : <Representation: CL_ADJUST, [Facet(type=FacetType(is_sequence='false', min_length=1, max_length=1, min_value=None, max_value=None, start_value=None, end_value=None, interval=None, time_interval=None, decimals=None, pattern=None, start_time=None, end_time=None, sentinel_values=None), value=None, value_type=<FacetValueType.string: 1>)]>
order : 7
pop_annotation : <bound method AnnotableArtefact.pop_annotation of <Dimension TC_ADJUST>>
uri : None
urn : urn:sdmx:org.sdmx.infomodel.datastructure.Dimension=BIS:BIS_TOTAL_CREDIT(2.0).TC_ADJUST
============================================================
ID: TIME_PERIOD
annotations : []
compare : <bound method Comparable.compare of <TimeDimension TIME_PERIOD>>
concept_identity : TIME_PERIOD
eval_annotation : <bound method AnnotableArtefact.eval_annotation of <TimeDimension TIME_PERIOD>>
get_annotation : <bound method AnnotableArtefact.get_annotation of <TimeDimension TIME_PERIOD>>
id : TIME_PERIOD
local_representation : <Representation: None, [Facet(type=FacetType(is_sequence=None, min_length=None, max_length=None, min_value=None, max_value=None, start_value=None, end_value=None, interval=None, time_interval=None, decimals=None, pattern=None, start_time=None, end_time=None, sentinel_values=None), value=None, value_type=<FacetValueType.observationalTimePeriod: 18>)]>
order : 8
pop_annotation : <bound method AnnotableArtefact.pop_annotation of <TimeDimension TIME_PERIOD>>
uri : None
urn : urn:sdmx:org.sdmx.infomodel.datastructure.TimeDimension=BIS:BIS_TOTAL_CREDIT(2.0).TIME_PERIOD

In [ ]:
dimensions = []

for dim in dsd.dimensions:

    # Linked codelist (if present)
    codelist = None

    if dim.local_representation and dim.local_representation.enumerated:
        codelist = dim.local_representation.enumerated.id

    dimensions.append(
        {
            "Order": dim.order,
            "Dimension ID": dim.id,
            "Dimension Name": str(dim.concept_identity.name),
            "Dimension Type": type(dim).__name__,
            "Codelist": codelist
        }
    )

df_dimensions = (
    pd.DataFrame(dimensions)
      .sort_values("Order")
      .reset_index(drop=True)
)

df_dimensions

   Order   Dimension ID        Dimension Name Dimension Type         Codelist
0      1           FREQ             Frequency      Dimension          CL_FREQ
1      2  BORROWERS_CTY    Borrowers' country      Dimension          CL_AREA
2      3   TC_BORROWERS      Borrowing sector      Dimension  CL_TC_BORROWERS
3      4     TC_LENDERS        Lending sector      Dimension    CL_TC_LENDERS
4      5      VALUATION      Valuation method      Dimension     CL_VALUATION
5      6      UNIT_TYPE             Unit type      Dimension      CL_BIS_UNIT
6      7      TC_ADJUST            Adjustment      Dimension        CL_ADJUST
7      8    TIME_PERIOD  Time period or range  TimeDimension             None

## Explanation of df_dimensions - columns and their purpose


| Column             | Purpose                                                                          |
| ------------------ | -------------------------------------------------------------------------------- |
| **Order**          | Determines the sequence of values in an SDMX data key.                           |
| **Dimension ID**   | Used when constructing SDMX API queries.                                         |
| **Dimension Name** | Human-readable description of the dimension.                                     |
| **Dimension Type** | Indicates whether it's a regular dimension or the special time dimension.        |
| **Codelist**       | References the set of allowed values, which you'll explore in the next notebook. |

### ***********************
### Exploring Measures
### ***********************

In [34]:
first_mes = dsd.measures[0]

print(type(first_mes))

print(first_mes)

print(dir(first_mes))

<class 'sdmx.model.v21.PrimaryMeasure'>
OBS_VALUE
['__annotations__', '__class__', '__contains__', '__dataclass_fields__', '__dataclass_params__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__firstlineno__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__match_args__', '__module__', '__ne__', '__new__', '__post_init__', '__reduce__', '__reduce_ex__', '__replace__', '__repr__', '__setattr__', '__sizeof__', '__slots__', '__static_attributes__', '__str__', '__subclasshook__', '__weakref__', '_preserve', '_urn', 'annotations', 'compare', 'concept_identity', 'eval_annotation', 'get_annotation', 'id', 'local_representation', 'pop_annotation', 'uri', 'urn']

In [38]:
# ----------------------------------------------------
# Inspect every property
# ----------------------------------------------------

for mes in dsd.measures:
    print("=" * 80)
    print(f"Measure ID : {mes.id}")

    for attr in dir(mes):
        if attr.startswith("_"):
            continue

        try:
            value = getattr(mes, attr)
            print(f"{attr:25}: {value}")
        except AttributeError:
            pass

================================================================================
Measure ID : OBS_VALUE
annotations              : []
compare                  : <bound method Comparable.compare of <PrimaryMeasure OBS_VALUE>>
concept_identity         : OBS_VALUE
eval_annotation          : <bound method AnnotableArtefact.eval_annotation of <PrimaryMeasure OBS_VALUE>>
get_annotation           : <bound method AnnotableArtefact.get_annotation of <PrimaryMeasure OBS_VALUE>>
id                       : OBS_VALUE
local_representation     : <Representation: None, [Facet(type=FacetType(is_sequence='false', min_length=None, max_length=15, min_value=None, max_value=None, start_value=None, end_value=None, interval=None, time_interval=None, decimals=None, pattern=None, start_time=None, end_time=None, sentinel_values=None), value=None, value_type=<FacetValueType.string: 1>)]>
pop_annotation           : <bound method AnnotableArtefact.pop_annotation of <PrimaryMeasure OBS_VALUE>>
uri                      : None
urn                      : urn:sdmx:org.sdmx.infomodel.datastructure.Measure=BIS:BIS_TOTAL_CREDIT(2.0).OBS_VALUE

In [40]:
rep = mes.local_representation

print(type(rep))
print(rep)
print(dir(rep))

<class 'sdmx.model.common.Representation'>
<Representation: None, [Facet(type=FacetType(is_sequence='false', min_length=None, max_length=15, min_value=None, max_value=None, start_value=None, end_value=None, interval=None, time_interval=None, decimals=None, pattern=None, start_time=None, end_time=None, sentinel_values=None), value=None, value_type=<FacetValueType.string: 1>)]>
['__annotations__', '__class__', '__dataclass_fields__', '__dataclass_params__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__firstlineno__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__match_args__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__replace__', '__repr__', '__setattr__', '__sizeof__', '__static_attributes__', '__str__', '__subclasshook__', '__weakref__', 'enumerated', 'non_enumerated']

In [41]:
for attr in dir(rep):
    if attr.startswith("_"):
        continue

    try:
        print(f"{attr:25}: {getattr(rep, attr)}")
    except Exception:
        pass

enumerated               : None
non_enumerated           : [Facet(type=FacetType(is_sequence='false', min_length=None, max_length=15, min_value=None, max_value=None, start_value=None, end_value=None, interval=None, time_interval=None, decimals=None, pattern=None, start_time=None, end_time=None, sentinel_values=None), value=None, value_type=<FacetValueType.string: 1>)]

In [42]:
measures = []

for mes in dsd.measures:

    # Default values
    data_type = None
    max_length = None

    # Extract information from the non-enumerated representation
    if (
        mes.local_representation is not None
        and mes.local_representation.non_enumerated
    ):
        facet = mes.local_representation.non_enumerated[0]
        data_type = facet.value_type.name
        max_length = facet.type.max_length

    measures.append({
        "Measure ID": mes.id,
        "Measure Name": str(mes.concept_identity.name),
        "Measure Type": type(mes).__name__,
        "Data Type": data_type,
        "Max Length": max_length,
        "URN": mes.urn
    })

df_measures = (
    pd.DataFrame(measures)
      .reset_index(drop=True)
)

df_measures

,Measure ID,Measure Name,Measure Type,Data Type,Max Length,URN
0,OBS_VALUE,Observation Value,PrimaryMeasure,string,15,urn:sdmx:org.sdmx.infomodel.datastructure.Meas...